version: '3.8'
services:
  db:
    image: mysql:8
    container_name: mysql-store
    environment:
      MYSQL_ROOT_PASSWORD: MyPassword!
      MYSQL_DATABASE: store_api
    ports:
      - "3306:3306"
    volumes:
      - mysql_store_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/store_api?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: MyPassword!
    ports:
      - "8080:8080"
volumes:
  mysql_store_data: