spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: false
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200 # 2h
    refreshTokenExpiration: 604800 # 7days
stripe:
  secretKey: ${STRIPE_API_KEY}

server:
  port: 8080

websiteUrl: http://localhost:3000